# Setting up the colors and copy/paste
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

# style
set -g status-style "fg=#665c54"
set -g status-bg default

# Remap split horizontal from % to h
unbind %
bind h split-window -h

# Remap split vertical from " to v
unbind '"'
bind v split-window -v

# Switch panes using the Meta key (usually Alt) prefix-free
bind -n C-l select-pane -L
bind -n C-h select-pane -R
bind -n C-k select-pane -U
bind -n C-j select-pane -D

# Clear srcreen
bind -n M-c send-keys 'C-l'

# Switch windows alt+number
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
