vim9script

# -----------------------------------------------
# --- plugins ---
# -----------------------------------------------
if empty(glob('~/dot/nvim/autoload/plug.vim'))
    silent !curl -fLo ~/dot/nvim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    au VimEnter * PlugInstall --sync | source $MYVIMRC
endif

plug#begin()
Plug 'junegunn/vim-easy-align'
Plug 'junegunn/fzf.vim'
# {{{
g:fzf_vim = {}
# g:fzf_vim.preview_window = ['hidden,right,40%,<70(up,40%)', 'ctrl-l']

def BuildQfList(lines: string)
    call setqflist(map(copy(lines), '{ "filename": v:val, "lnum": 1 }'))
    copen
    cc
enddef

g:fzf_action = {
    'ctrl-q': function('BuildQfList'),
    'ctrl-t': 'tab split',
    'ctrl-x': 'split',
    'ctrl-v': 'vsplit'
}

g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }
# }}}
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-sleuth' # Buffer options
Plug 'tpope/vim-endwise' # Insert endif
Plug 'tpope/vim-capslock'
Plug 'tpope/vim-eunuch' # UNIX helper
Plug 'airblade/vim-rooter'
# {{{
g:rooter_silent_chdir = 1
g:rooter_paterns = [
    '.git',
    '_darcs',
    '.hg',
    '.bzr',
    '.svn',
    'Makefile',
    'package.json',
    '.gitignore',
    'Makefile',
]
# }}}
Plug 'chrisbra/Colorizer'
Plug 'mg979/vim-visual-multi'
# {{{
g:VM_maps = {
    'Find Under': '<C-q>',
    'Find Subword Under': '<C-q>'
}
# }}}
Plug 'lacygoill/vim9asm'
Plug 'girishji/vimcomplete'
# {{{
g:vimcomplete_tab_enable = 1
var comp_options = {
    completor: { alwaysOn: false,  shuffleEqualPriority: false, postfixHighlight: true },
    buffer: { enable: true, priority: 8, urlComplete: true, envComplete: true },
    abbrev: { enable: true, priority: 9 },
    lsp: { enable: true, priority: 10, maxCount: 5 },
    # omnifunc: { enable: false, priority: 8, filetypes: ['python', 'javascript'] },
    # vsnip: { enable: true, priority: 11 },
    vimscript: { enable: true, priority: 11 },
}
autocmd VimEnter * g:VimCompleteOptionsSet(comp_options)
# }}}
Plug '~/.vim/local/vim-shout'
Plug '~/.vim/local/lsp'
Plug '~/.vim/local/taghighlight'
# {{{
var lspOpts = {
    semanticHighlight: false,
    aleSupport: false,
    autoHighlight: false,
    autoHighlightDiags: true,
    autoPopulateDiags: false,
    completionMatcher: 'icase',
    completionMatcherValue: 1,
    echoSignature: true,
    hideDisabledCodeActions: false,
    highlightDiagInline: false,
    hoverInPreview: false,
    ignoreMissingServer: true,
    keepFocusInDiags: false,
    keepFocusInReferences: true,
    completionTextEdit: false,
    diagVirtualTextAlign: 'above',
    diagVirtualTextWrap: 'default',
    noNewlineInCompletion: false,
    autoComplete: false,
    omniComplete: true,
    outlineOnRight: false,
    outlineWinSize: 20,
    showDiagInBalloon: true,
    showDiagInPopup: true,
    showDiagOnStatusLine: false,
    showDiagWithSign: true,
    showDiagWithVirtualText: false,
    showInlayHints: false,
    showSignature: true,
    snippetSupport: false,
    ultisnipsSupport: false,
    useBufferCompletion: false,
    usePopupInCodeAction: false,
    useQuickfixForLocations: true,
    vsnipSupport: false,
    bufferCompletionTimeout: 0,
    customCompletionKinds: false,
    completionKinds: {},
    filterCompletionDuplicates: false,
}

def LspOnAttach()
    # so we can use :stag
    setlocal tagfunc=lsp#lsp#TagFunc

    # nmap <buffer> gd  <cmd>LspGotoDefinition<cr>
    nmap <buffer> K   :LspHover<cr>
    nmap <buffer> ]d  :LspDiagNext<cr>
    nmap <buffer> [d  :LspDiagPrev<cr>
    nmap <buffer> gh  :LspDiagCurrent<cr>
    nmap <buffer> gla :LspCodeAction<cr>
    nmap <buffer> gls :LspSwitchSourceHeader<cr>
enddef

autocmd User LspSetup call LspOptionsSet(lspOpts)
autocmd User LspSetup call LspAddServer(lspServers)
autocmd User LspAttached call LspOnAttach()
# }}}
# {{{
var lspServers = [
    {
        name: 'clangd',
        filetype: ['c', 'cpp'],
        path: 'clangd',
        args: [
        '--background-index',
        "--malloc-trim",
        "--enable-config",
        "--all-scopes-completion=true",
        "--completion-style=detailed",
        "--function-arg-placeholders",
        "--header-insertion=iwyu",
        "--header-insertion-decorators",
        ]
    },
]
# }}}
Plug 'J-Merle/vim-todo'
Plug 'habamax/vim-dir'
plug#end()

packadd! comment
packadd! termdebug
# packadd! matchit

runtime ftplugin/man.vim
# disable matchparent and use plugin/parenmatch.vim
g:loaded_matchparen = 1
g:loaded_matchparen9 = 1
# g:loaded_parenmatch = 1

# -----------------------------------------------
# --- options ---
# -----------------------------------------------
# experimental
# set regexpengine=1
set lazyredraw

# timeout for key sequences of terminal like esc and such
set nocompatible ttimeout ttimeoutlen=0
set history=10000
# Undo file shouldn't replace version control
set noswapfile

set undofile
silent system("mkdir -p /tmp/$USER.vim9undo")
set undodir=/tmp/$USER.vim9undo
# speed things up
set hidden
set notitle
# mouse support
set mouse=ar
# Essential for scroll to work properly
set ttymouse=sgr
# remedy flikering wiht termguicolors `https://github.com/vim/vim/issues/10574`. I'm not
# sure how effective this one is, but setting Normal guibg=NONE definitly make vim flicker.
set t_ut=
set completeopt=menu,popuphidden,noinsert
set pumheight=6 previewheight=10
# behave like bash
set nowildmenu wildignorecase wildmode=longest,list,full
set showcmd
set showmode
set signcolumn=no
set ruler
set nocursorline
set scrolloff=3
set scrolljump=0

# set showcmd showcmdloc=statusline
set shortmess=aoOFtT
set shortmess-=S
set splitbelow splitright
set incsearch hlsearch
set ignorecase
set smartcase
set smartindent
# when unset you can delete inserted tab with C-w without deleting the word before it
set nosmarttab
set expandtab shiftwidth=4 tabstop=4
set backspace=indent,eol,start
set foldmethod=marker
set textwidth=100
set jumpoptions=stack
set showbreak=↷
set fillchars+=diff:╱,vert:│
set listchars=tab:»\ ,trail:-
set nolist

# Sane indentation
set cinoptions+=:0,ls,g0,N-s,E-s,(s,k0,j1,J1

# put the more unlikey first so that when it is the case you search that first.
set path=.,**,/usr/src/*/include,/usr/include

# if match case is not set to `match` tag search becomes really slow!
set tagcase=match

if executable('rg')
    set grepprg=rg\ -H\ --no-heading\ --vimgrep
    set grepformat=%f:%l:%c:%m
endif

set laststatus=2
if &laststatus > 0
    set showcmdloc=statusline
    set statusline=
    # Left
    set stl+=%f
    set stl+=%(\ %m%q%h%w%r%)
    set stl+=\ \ \ \ %P\ %10(%l:%c\ \ %)
    # set stl+=%(\ \ \ \ Git:%{v:lua.GitSignsStatus()}%)
    # set stl+=%(\ \ \ \ LSP:%{v:lua.GetRunningLsp()}%{%v:lua.GetDiag()%}%)
    # Middle
    set stl+=\ %=
    set stl+=%S
    # Right
    set stl+=\ %=
    set stl+=
else
    set rulerformat=%60(%([%{%v:lua.GetRunningLsp()%}%{%v:lua.GetDiag()%}]%)\ \ \ \ %(Git:%{v:lua.GitSignsStatus()}%)%=\ \ \ \ %-8(%l,%c%)\ %P%)
    augroup ruler
        autocmd BufEnter * call feedkeys("\<C-g>")
    augroup end
endif

if has('gui')
    set guifont=Inconsolata\ 15

    # gui keympas
    noremap <M-1> <cmd>tabn1<cr>
    noremap <M-2> <cmd>tabn2<cr>
    noremap <M-3> <cmd>tabn3<cr>
    noremap <M-4> <cmd>tabn4<cr>
    noremap <M-5> <cmd>tabn5<cr>
    noremap <M-6> <cmd>tabn6<cr>
    noremap <M-7> <cmd>tabn7<cr>
    noremap <M-8> <cmd>tabn8<cr>
    noremap <M-9> <cmd>tabn9<cr>
endif

g:mapleader = " "

# -----------------------------------------------
# --- coloring ---
# -----------------------------------------------
# mark trailing spaces as errors using highlight group CursorLine
match CursorLine '\s\+$'
filetype plugin indent on
syntax on
set termguicolors
set background=dark
color lightgruv
# hi normal guibg=black

# -----------------------------------------------
# --- keymaps ---
# -----------------------------------------------
map ' `

inoremap <silent> <Esc> <Esc>g`^
inoremap <C-z> <C-x>s
# :help map-special-keys
inoremap <C-_> <esc>ugi
# for accepting auto complete
inoremap <C-^> <esc><C-^>
inoremap <C-s> <Plug>CapsLockToggle
inoremap <C-x>d <esc>:r!date "+\%Y/\%m/\%d \%H:\%M:\%S"<cr>kJg`]a

inoremap <expr> <C-j> pumvisible() ? "\<C-n>" : "\<C-j>"
inoremap <expr> <C-k> pumvisible() ? "\<C-p>" : "\<C-k>"

def g:Comp()
    if pumvisible()
        feedkeys("\<C-y>")
    else
        feedkeys("\<C-space>")
        timer_start(50, (_) => feedkeys("\<C-n>"))
    endif
enddef

inoremap <C-f> <scriptcmd>g:Comp()<cr>

tmap <C-]> <C-\><C-n>

# yank
map Y yg_

# nnoremap yif mzggVGyg`z
# nnoremap yap yap}
# nnoremap yip yip}
# nnoremap y} y}}
# nnoremap y{ y{

map gy "+y
map gY "+Y

nnoremap p :let @c=col('.')<cr>]p:call cursor(0, <C-r>c)<cr>
nnoremap P :let @c=col('.')<cr>]P:call cursor(0, <C-r>c)<cr>
# vnoremap y   mzyg`z
# vnoremap gy  mz"+yg`z
# paste, goto pase start, mark it, select pasted lines, reindent, go back to
# marked pase
# noremap p p`[mzV`]=`z
# noremap P P`[mzV`]=`z
noremap gp "+p
noremap gP "+P
nnoremap yo :let @+=@"<cr>

# indent
nmap     +   mz[%=%g`z
imap   <C-b> <esc>+gi
nnoremap =if mzggVG=g`z
nnoremap =ap mz=apg`z
nnoremap =ip mz=ipg`z
nnoremap ==  mz=ipg`z
vnoremap =   mz=g`z

# format
nnoremap gqif mzggVGgqgg`z
nnoremap gqap mzgqapg`z
nnoremap gqip mzgqipg`z
nnoremap gql  mzgqlg`z
vnoremap gq   mzgqg`z
noremap  gz   1z=
noremap  zs   mz:%s/\s\+$//e<cr>''g`z
nnoremap gF   mz:%!clang-format<cr>g`z
nmap gcA      gcc^dWA <C-r>"
nmap gcd      :let @c=col('.')<cr>yygccp:call cursor(0, <C-r>c)<cr>

nnoremap ga <plug>(EasyAlign)
xnoremap ga <plug>(EasyAlign)
nnoremap ga\ mz<plug>(EasyAlign)ap\g`z

# navigation
noremap j gj
noremap k gk
noremap <C-h> <cmd>tabp<cr>
noremap <C-l> <cmd>tabn<cr>
noremap <C-j> <cmd>cn<cr>
noremap <C-k> <cmd>cp<cr>
noremap <M-q> g`Qg`"
noremap <M-w> g`Wg`"
noremap <M-e> g`Eg`"
noremap <M-r> g`Rg`"
noremap <M-t> g`Tg`"

# noremap gd [<C-I>
noremap <silent> gd <cmd>call JumpToDefinition()<cr>
noremap <C-w>d      <cmd>call SplitJumpToDefinition()<cr>
# nnoremap <C-W>gd <Cmd>:vert call JumpToDefinition()<CR>
noremap gn ]<C-I>
noremap <expr> gk exists(":Man") > 0 ? ":vert Man <cword><CR>" : "K"
nnoremap * *N
xnoremap * y/\M<C-R>"<cr>N
nnoremap # #N
xnoremap # y?\M<C-R>"<cr>N
noremap n nzz
noremap N Nzz
noremap <C-w>t :belowright term<cr>

# cmd
cmap <C-x>f <C-r>=expand('%:p')<cr>
# cmap <C-x>d <C-r>=expand('%:p:h').'/'<cr>
cmap <C-x>d <C-r>=expand('%:p:h:s?\S\+:\/\/??').'/'<cr>
cmap <C-x>r redir<space>@l\|<space>\|redir<space>end<C-left><C-left>
cmap <C-j> <Down>
cmap <C-k> <Up>

# fast access
nnoremap <leader>d :Bdelete<cr>
nmap     <leader>b :b<space>
nmap     <leader>e :e<space><C-x>d
# nmap     <leader>e :Dir<space><C-x>d
nmap     <leader>E :Exp<cr>
nmap     <leader>h :h<space>
noremap  <leader>f <cmd>Files<cr>
nmap     <leader>F :Files<space><C-x>d
noremap  <leader>r <cmd>Histor<cr>
noremap  <leader>B <cmd>Buffers<cr>
noremap  <leader>H <cmd>Helptags<cr>
noremap  <leader>t :Tags <C-r><C-w><cr>
noremap  <leader>T <cmd>Tags<space>
# for now use grep!
nnoremap <leader>g :RF <C-r><C-w><cr>
xnoremap <leader>g :<C-u>RF <C-r>=escape(GetVisualSelection(), "()\+*.[]\|")<cr><cr>
# nnoremap <leader>G <cmd>RG<cr>
nnoremap <leader>G <cmd>RF<cr>

nnoremap <leader>vv :Git<cr>

nnoremap cc :wa<cr>:Term <C-r>=get(t:, 'term_cmd', '')<cr>
nnoremap sn :Term<space>
nnoremap ss <cmd>TermToggleWin<cr>
nnoremap sq <cmd>TermToQf<cr>
nnoremap sx <cmd>TermKill<cr>
nnoremap sj <cmd>TermNextErrorJump<cr>
nnoremap sk <cmd>TermPrevErrorJump<cr>
nnoremap sJ <cmd>TermLastErrorJump<cr>
nnoremap sK <cmd>TermFirstErrorJump<cr>
nnoremap s<cr> <cmd>TermThisErrorJump<cr>

# substitute
nnoremap <C-s>s  :s/<C-R>=expand('<cword>')<cr>//g<Left><Left>
xnoremap <C-s>s  :s//g<Left><Left>
nnoremap <C-s>f  :%s/<C-R>=expand('<cword>')<cr>//g<Left><Left>
xnoremap <C-s>f  y:<C-w>%s/<C-r>"//g<Left><Left>
nnoremap <C-s>h  :'<,'>:s/<C-R>=expand('<cword>')<CR>//g<Left><Left>
nnoremap <C-s>ip yiwvip<Esc>:'<,'>:s/<C-R>"//g<Left><Left>
nnoremap <C-s>ap yiwvap<Esc>:'<,'>:s/<C-R>"//g<Left><Left>

# Miscellaneous
noremap <C-g>  1<C-g>
# CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
# so that you can undo CTRL-U after inserting a line break.
# Revert with ":iunmap <C-U>".
inoremap <C-U> <C-G>u<C-U>
# nohighlight
nnoremap <Esc> <cmd>noh<cr>
nnoremap c; :<C-p>

# change hex to [s]ymbol
def! g:HexToSymbol(hex: string)
    exec 'normal iU' .. hex .. ' '
enddef
nnoremap cs diw:call HexToSymbol(expand(@@))<cr>

# Visual
def ForceBlockwise(next_key: string): string
    const setup_keyseq_table = {
        'I':  {'v': "\<C-v>I",  'V': "\<C-v>^o^I", "\<C-v>": 'I'},
        'A':  {'v': "\<C-v>A",  'V': "\<C-v>0o$A", "\<C-v>": 'A'},
        'gI': {'v': "\<C-v>0I", 'V': "\<C-v>0o$I", "\<C-v>": '0I'},
    }
    return setup_keyseq_table[next_key][mode()]
enddef

xmap <expr> I  ForceBlockwise('I')
xmap <expr> gI ForceBlockwise('gI')
xmap <expr> A  ForceBlockwise('A')

# -----------------------------------------------
# --- auto cmds ---
# -----------------------------------------------
augroup autoCommands
    autocmd!
    autocmd BufWritePost */.vim/**/*.vim,.vimrc,vimrc,*/vim/**/*.vim source %
    # this option is set by ftplugin for each file type. I just want a consistant format option
    # across all file types thus the autocmd.
    # defaults: tcroql
    autocmd BufEnter * set formatoptions=tcrqljn1p
    # Mark `"` is the position when last exiting the current buffer.
    autocmd BufReadPost *
                \ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
                \ |   exe "normal! g`\"zz"
                \ | endif

    autocmd Filetype tex,text,markdown,gitcommit setlocal spell
    autocmd Filetype qf nmap <buffer> <Esc> ZQ
    autocmd BufAdd .clang* set filetype=yaml
    # for the v command in bash vi mode
    autocmd BufAdd /tmp/bash* set filetype=sh

    autocmd BufWinEnter man://* call MoveOpenedWinodwToSaneSplit()
    autocmd Filetype fugitive call MoveOpenedWinodwToSaneSplit()
    autocmd BufWinEnter */doc/*.txt call MoveOpenedWinodwToSaneSplit()

    # autocmd WinEnter,WinLeave,WinNew * redrawstatus!

    autocmd CmdwinEnter * nmap <buffer> q     :q<cr>
    autocmd CmdwinEnter * nmap <buffer> <C-c> :q<cr>

    autocmd VimResume,BufEnter,WinEnter,VimEnter * call g:TmuxApplyTitle()
    autocmd VimLeave,VimSuspend * call g:TmuxResetTitle()
augroup end

# -----------------------------------------------
# --- cmds ---
# -----------------------------------------------
# Convenient command to see the difference between the current buffer and the
# file it was loaded from, thus the changes you made.
command! DiffOrig vert new | set bt=nofile | r ++edit %% | 0d_ | diffthis | wincmd p | diffthis
command! RT RooterToggle | exec "norm :\<C-u>cd \<C-x>d\<cr>"

def BufWordsComplete(A: string, L: string, P: number): string
    return join(uniq(sort(split(join(getline(1, '$'), "\n")))), "\n")
enddef

command! -nargs=1 -complete=custom,BufWordsComplete Grep call shout#CaptureOutput("rg -S --vimgrep " .. <f-args>)
command! -nargs=1 -complete=file Dump call shout#CaptureOutput("objdump -C -l -S -d --disassembler-color=off" .. <f-args>, "[dump]", "asm")
command! -nargs=1 -complete=file Assembly call shout#CaptureOutput(<f-args>  .. " -o- -S -fverbose-asm", "[asm]", "asm")
command! -nargs=1 -complete=file PreProc call shout#CaptureOutput(<f-args>  .. " -o- -E", "[PreProc]", "c")


# -----------------------------------------------
# --- functions ---
# -----------------------------------------------
def g:UseSplitOrCreate(): number
    var current_win_pos = win_screenpos(0)
    var winnr = winnr()

    if &columns > 160
        if winnr != winnr('1l')
            return win_getid(winnr('1l'))
        elseif winnr != winnr('1h')
            return win_getid(winnr('1h'))
        else
            :botright vsplit
            :wincmd p
            return win_getid(winnr('#'))
        endif
    else
        if winnr != winnr('1j')
            return win_getid(winnr('1j'))
        elseif winnr != winnr('1k')
            return win_getid(winnr('1k'))
        else
            :botright split
            :wincmd p
            return win_getid(winnr('#'))
        endif
    endif
enddef

def g:MoveOpenedWinodwToSaneSplit()
    var prev_winnr = winnr('#')
    if prev_winnr == 0 | return | endif

    var split_to_use = g:UseSplitOrCreate()
    if win_getid(prev_winnr) == split_to_use | return | endif

    var bufnr = bufnr('%')
    var view = winsaveview()
    var old_win_id = win_getid()

    win_gotoid(split_to_use)

    exec "buffer " .. bufnr
    winrestview(view)
    win_execute(old_win_id, 'close')
enddef

var tmuxapplytimer = 0
def g:TmuxApplyTitle()
    if !!tmuxapplytimer | return | endif
    tmuxapplytimer = timer_start(200, (_) => {
        silent system("tmux rename-window \"[" .. expand("%:t") .. "]\"")
        tmuxapplytimer = 0
    })
enddef

def g:TmuxResetTitle()
     silent system("tmux set-window-option automatic-rename on")
enddef

# Get highlight groups of word under cursor in Vim
def g:Syn()
    for id in synstack(line("."), col("."))
        echo synIDattr(id, "name")
    endfor
enddef
command! Syn call Syn()

def g:GetVisualSelection(): string
    var mode = mode()
    var start: list<number>
    var end: list<number>

    if mode == 'v' || mode == 'V' || mode == "\<C-V>"
        # getpos() -> [bufnum, lnum, col, off]
        start = getpos('.')
        end = getpos('v')

        if mode == 'V'
            start[2] = 1
            end[2] = 999
        endif
    else
        start = getpos("'<")
        end = getpos("'>")
    endif

    var lines = getline(start[1], end[1])
    if len(lines) <= 0
        return ''
    endif

    lines[-1] = strpart(lines[-1], 0, end[2])
    lines[0] = strpart(lines[0], start[2] - 1)

    var content = join(lines)
    return content
enddef

def g:FzfChistory(): list<string>
    var hlist = execute("chistory")
    #echo hlist

    var src = split(hlist, '\n')
    src = map(src, (_, v): string => {
        return substitute(v, '^\(>*\s*\)[^0-9]*\|\sof\s[0-9]\|errors', '\1\ ', 'g')
    })

    return fzf#run(fzf#wrap('chistory', { 'source': src, 'sink': (num) => execute(num[3] .. "chistory") } ))
enddef

def g:FzfRg()
    var selection: string
    var buf: number

    buf = term_start('Rg --height 100%', { close_cb: (channel) => {
        selection = term_getline(buf, 1)->substitute('^\(\S\{-}\):\(\d\+\):\(\d\+\).*', '+normal!\\ j\2l\3 \1', 'g')
        execute('bwipeout ' .. buf)
        :exe $'edit {selection}'
    }})
enddef
command! -nargs=0 Rgg call FzfRg()

def g:RipgrepFzf(query: string, fullscreen: bool)
    var command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
    var prompt = ''
    var initial_grep = printf(command_fmt, shellescape(query))
    var reload_grep = printf(command_fmt, '{q}')
    var options = {'options': [
        '--prompt', '*Rg> ',
        '--header', getcwd(),
        '--header-first',
        '--phony',
        '--query', query,
        '--bind', 'change:reload:sleep 0.1;' .. reload_grep,
        '--bind', 'ctrl-g:transform:[[ ! {fzf:prompt} == "*Rg> " ]] &&' ..
        'echo "rebind(change)+change-prompt(*Rg> )+disable-search+transform-query:echo \{q} > /tmp/rg-fzf-f; cat /tmp/rg-fzf-r" ||' ..
        'echo "unbind(change)+change-prompt({q}> )+enable-search+transform-query:echo \{q} > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f"'
    ]}
    call fzf#vim#grep(initial_grep, 1, fzf#vim#with_preview(options), fullscreen)
enddef
command! -nargs=* -bang RF call RipgrepFzf(<q-args>, <bang>0)

def g:Time(count: number, ...args: list<string>)
    echom args
    var repeat = (count <= 0 ? 1 : count)
    var k = 0
    var start = reltime()
    while k < repeat
        exe join(args)
        k += 1
    endwhile
    var time = reltimestr(reltime(start))

    redraw

    if repeat == 1
        echomsg "Execution took " .. time .. " sec."
    else
        echomsg repeat .. " repetitions took " .. time .. " sec."
    endif
enddef
command! -nargs=* -count -complete=expression Time :call Time(<count>, <q-args>)

# Scratch
# {{{
def g:JumpTag()
    var start_bnr = bufnr()
    var start_line = line('.')
    execute("normal! \<C-]>")
    # if we didn't jump anywhere. try jumping whith [count]=2
    if bufnr() == start_bnr && line('.') == start_line
        execute("normal! \<C-t>2\<C-]>")
    endif
enddef

# "~/dev/handmade/src/main.h" 3L, 34B
# "/usr/include/SDL2/SDL_video.h" [RO] 2184L, 81088B
# "include/SDL2/SDL_video.h" [RO] 2184L, 81088B

def g:JumpToDefinition()
    var fallbacks = [
        'LspGotoDefinition',
        'call JumpTag()',
        'normal! gd',
        'normal! [\<C-I>',
    ]

    for cmd in fallbacks
        try
            var s = execute(cmd)
            # echomsg $'s: {s}'
            if strlen(s) < 2 || s =~? '"\([\~\/]\|\S\+\/\)\S\+"\s.*'
                echomsg $'used {cmd}'
                break
            endif
        catch
            # echomsg $'we catched on: {cmd}: {v:exception}'
            continue
        endtry
    endfor
enddef

def g:SplitJumpToDefinition()
    execute 'split g:JumpToDefinition()'
    g:MoveOpenedWinodwToSaneSplit()
enddef

def OpenCommandPalette()
    var windowId = popup_create(term_start([&shell], {hidden: 1, term_finish: 'close'}), { border: [1, 1, 1, 1], minwidth: winwidth(0) / 2, minheight: &lines / 2 })
enddef

command CommandPalette call OpenCommandPalette()

def g:IsSearchedWord(): bool
    return expand('<cword>') =~ @/
enddef

# Very interesting! any way to do this for forexample =
# def g:OpFuncSteady()
#     if !empty(&operatorfunc)
#         if !!get(b:, 'opfuncview')
#             winrestview(b:opfuncview)
#         endif
#         b:opfuncview = {}
#         noautocmd set operatorfunc
#     endif
# enddef

# augroup opfunc
#     autocmd!
#     autocmd OptionSet operatorfunc b:opfuncview = winsaveview()
#     autocmd CursorMoved * g:OpFuncSteady()
# augroup END

# }}}

defcompile
