vim9script

set nocompatible
set ttimeout ttimeoutlen=0
set history=1000 termwinscroll=1000000
set hidden noswapfile undofile undodir=/tmp/$USER.vim9undo | silent system("mkdir -p /tmp/$USER.vim9undo")
set mouse=ar ttymouse=sgr
set completeopt=menu,longest
set nowildmenu wildignorecase wildmode=longest,list,full wildcharm=<Tab>
set notitle showcmd shortmess=aoOFtT
set nostartofline splitbelow splitright
set hlsearch incsearch ignorecase smartcase tagcase=match # if match case is not set to `match` tag search becomes really slow!
set smartindent nosmarttab expandtab shiftwidth=4 tabstop=4
set fillchars+=diff:╱,fold:\ ,vert:│
set list listchars=tab:\ ,nbsp:␣,trail:·,extends:…,precedes:… showbreak=\
set cpoptions+=n
set cinoptions+=:0,ls,g0,N-s,E-s,(s,k0,j1,J1,t0
set path=.,**,/usr/include
set grepprg=grep\ -rn
set termguicolors

color lightgruv

g:loaded_netrw = 1 | g:loaded_matchparen = 1 | g:loaded_vimballPlugin = 1
packadd! matchit
packadd! comment
plug#begin()
Plug 'junegunn/vim-easy-align'
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-fugitive'
Plug 'glts/vim-magnum'
Plug 'glts/vim-radical'
Plug 'alx741/vinfo'
Plug 'S4deghN/clrzr'
Plug 'mg979/vim-visual-multi'
Plug 'airblade/vim-rooter' | g:rooter_silent_chdir = 1 | g:rooter_patterns = [ '.git', '.svn', '.gitignore', 'tags']
Plug '~/.vim/local/vim-fm'
Plug '~/.vim/local/lsp' | runtime lsp.vim
plug#end()

map ' `
map gp "+p
map gP "+P
map +  =i{

noremap <C-j> <cmd>cn<cr>
noremap <C-k> <cmd>cp<cr>

noremap  } <cmd>keepj norm! }<cr>
noremap  { <cmd>keepj norm! {<cr>
noremap  n <cmd>keepj norm! nzz<cr>
noremap  N <cmd>keepj norm! Nzz<cr>
nnoremap * *<cmd>keepj norm! N<cr>
nnoremap # #<cmd>keepj norm! N<cr>
xnoremap * y/\V<C-R>"<cr><cmd>keepj norm! N<cr>
xnoremap # y?\V<C-R>"<cr><cmd>keepj norm! N<cr>

nnoremap yo  :let @+=@"<cr>
nnoremap gz  1z=
nnoremap ga  <plug>(EasyAlign)
xnoremap ga  <plug>(EasyAlign)
nnoremap ga\ mz<plug>(EasyAlign)ap<C-x>\\<cr>g`z
noremap  gk  :ManCword<cr>
nnoremap zs  :%s/\s\+$//e<cr>
nnoremap gL  <scriptcmd>utils#OpenLink(expand("<cfile>"))<cr>
nmap     gcd <cmd>let @c=col('.')<cr>yygccp<cmd>call cursor(0,@c)<cr>

noremap <C-g>  1<C-g>

exe "set <M-f>=\ef" | cmap <M-f>  <C-right>
exe "set <M-b>=\eb" | cmap <M-b>  <C-left>
cmap <C-j>  <Down>
cmap <C-k>  <Up>
cmap <C-x>f <C-r>=expand('%:p')<cr>
cmap <C-x>d <C-r>=expand('%:p:h:s?\S\+:\/\/??').'/'<cr>
cmap %% <C-x>f

tnoremap <C-]> <C-\><C-n>
tnoremap <ScrollWheelUp> <C-\><C-n><ScrollWheelUp>

nnoremap <space>d  :Bdelete<cr>
nmap     <space>b  :b<space><Tab>
nmap     <space>e  :e<space><C-x>d
nnoremap <space>E  :e ~/.vim/**/
nnoremap <space><C-e> :e $VIMRUNTIME/**/
nmap     <space>h  :h<space>
noremap  <space>f  <cmd>Files<cr>
nmap     <space>F  :Files<space><C-x>d
noremap  <space>r  <cmd>Histor<cr>
noremap  <space>B  <cmd>Buffers<cr>
noremap  <space>H  <cmd>Helptags<cr>
noremap  <space>t  :Tags <C-r><C-w><cr>
noremap  <space>T  <cmd>Tags<space>
nnoremap <space>g  <cmd>LiveGrep<cr>
nnoremap <space>G  :LiveGrep <C-r><C-w><cr>
vnoremap <space>g  :<C-u>LiveGrepVisual<cr>
nnoremap <space>vv :Git<cr>
nnoremap <space>vb <cmd>echo utils#GetGitBranch()<cr>
nnoremap <space>w  <scriptcmd>g:Dict(expand("<cword>"))<cr>
nnoremap <space>a  <cmd>Apropos<cr>
nnoremap <space>z  <cmd>setl spell!<cr>

command! Syn utils#Syn()
command! RT RooterToggle | exec "norm :\<C-u>cd \<C-x>d\<cr>"
command! -nargs=+ -complete=command  R put = execute(<q-args>)->trim()
command! -nargs=+ -complete=function RR put = execute('echo ' .. <q-args>)->trim()
command! -nargs=? Expand utils#KeepView(':%!expand -t ' .. (!<q-args> ? '4' : <q-args>), winsaveview(), 'c')
command! -nargs=1 -bang Grep g:Term("rg -S --vimgrep " .. <f-args>, <bang>0)
# Dump {binfile}
command! -nargs=1 -bang -complete=file Dump g:Term("objdump -ClSd --disassembler-color=on " .. <f-args>, <bang>0, "[dump]", "asm")
# Assembly {compiler} {sourcefile}
command! -nargs=1 -bang -complete=file Assembly g:Term(<f-args>  .. " -o- -S -fverbose-asm", <bang>0, "[asm]", "asm")
# PreProc {compiler} {sourcefile}
command! -nargs=1 -bang -complete=file PreProc g:Term(<f-args>  .. " -o- -E", <bang>0, "[PreProc]", "c")

augroup autoCommands
    autocmd!
    autocmd BufWritePost *.vim,vimrc source %
    autocmd BufReadPost * if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit' | exe "normal! g`\"zz" | endif
    # this option is set by ftplugin for each file type.
    # I just want a consistant format option across all file types thus the autocmd.
    autocmd BufEnter * set formatoptions=tcrqljn1p # default: tcroql
    autocmd BufWinEnter */doc/*.txt call utils#MoveOpenedWinodwToSaneSplit() | setl nolist

    autocmd Filetype qf nmap <buffer> <Esc> ZQ
    autocmd CmdwinEnter * nmap <buffer> q     :q<cr>
    autocmd CmdwinEnter * nmap <buffer> <C-c> :q<cr>

    autocmd BufAdd *.lub set filetype=lua
    autocmd BufAdd .clang* set filetype=yaml
    autocmd BufAdd /tmp/bash* set filetype=sh
augroup end
