add_newline = false

[line_break]
disabled = true
## FIRST LINE/ROW: Info & Status
# First param ─┌
[username]
format = "[$user]($style)@"
style_user = "bold red"
style_root = "bold red"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) "
style = "bold"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = "purple"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = ""
repo_root_style = "bold yellow"

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = true


## SECOND LINE/ROW: Prompt
# Somethere at the beginning
[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
disabled = true

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 15
style = "bold red"
disabled = true

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 50
style = "bold yellow"
disabled = true

[[battery.display]]  # "bold green" style when capacity is between 10% and 30%
threshold = 80
style = "bold green"
disabled = true

# Prompt: optional param 1
[time]
format = " 🕙 $time($style)\n"
time_format = "%T"
style = "bright-white"
disabled = true

# Prompt: param 2 └─
[character]
success_symbol = "[🥭 ➜](bold cyan) "
error_symbol = "[ ➜](bold red) "

# SYMBOLS
[status]
symbol = "🔴"
format = '[$symbol$status_common_meaning$status_signal_name$status_maybe_int]($style)'
map_symbol = true
disabled = false

[git_branch]
symbol = " "

[cmake]
disabled = true

[lua]
disabled = true

[aws]
symbol = " "
disabled = true

[conda]
symbol = " "
disabled = true

[dart]
symbol = " "
disabled = true

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[golang]
symbol = " "
disabled = true

[hg_branch]
symbol = " "
disabled = true

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[nim]
symbol = " "
disabled = true

[nix_shell]
symbol = " "
disabled = true

[nodejs]
symbol = " "
disabled = true

[package]
symbol = " "
disabled = true

[perl]
symbol = " "
disabled = true

[php]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
disabled = true

[swift]
symbol = "ﯣ "
disabled = true
